### ISSUE TITLE
shellvars burp on arrays of maps  (aka objects/hashes/collections/dicts) 

### ISSUE THREAD

**Issue by briceburg** [jasmith590/COP#17]
I'd like shellvars to support the following yaml input

```yml

---
machine: blah
hooks:
  - command: up
    script: aaa
  - command: down
    script: bbb
```

This works with JSON, e.g.
```
[nesta@acorn ~]$ badevops-cop test.yaml --json
{
  "machine": "blah",
  "hooks": [
    {
      "command": "up",
      "script": "aaa"
    },
    {
      "command": "down",
      "script": "bbb"
    }
  ]
}
```

but breaks on shell:

```
[nesta@acorn ~]$ badevops-cop test.yaml --shell
machine="blah"
hooks=( "[object Object]" "[object Object]" )
```

**Comment by jasmith590** [comment]
What about if we format the exported shell vars into something like this, that keeps the key of the array, but it will still follow our shell convention of parent/child relationship with "__"

```
machine="blah"
hooks__0_command="up"
hooks__0_script="aaa"
hooks__1_command="down"
hooks__1_script="bbb"
```

**Comment by briceburg** [comment]
@jasmith590 I think this approach may work, although not 100% sure how to handle nested arrays or maps. We'll need to do some parsing in the consuming script to make usable -- and it would help to non-zero index the array (start at 1).  Here's a sample using your output:

```sh
machine="blah"
hooks__1_command="up"
hooks__1_script="aaa"
hooks__2_command="down"
hooks__2_script="bbb"

while let i++; eval "vars=\"\${!hooks__${i}_*}\"" ; [ ! -z "$vars" ]; do
  echo "working with index $i"
  for var in $vars; do
    eval val=\$$var

    # remove prefix from var name
    var=${var//hooks__${i}_/}

    echo "  $var: $val"
  done
done
```

which outputs ==>

```
working with index 1
  command: up
  script: aaa
working with index 2
  command: down
  script: bbb
```

@SamTay thoughts?

**Comment by SamTay** [comment]
I mean.. I'm no bash expert but your example seems really fragile. Is it not? If you think that will work for dockmaster and not be a bitch to maintain, let's do it. But I think either way, handling data of arbitrary nesting is gonna be a pain since bash isn't really made to do that.. If you think it's worth reevaluating the language choice for dockmaster I am all ears.

**Comment by briceburg** [comment]
@SamTay not sure how to make this 'less' fragile. We need a way to consume arrays of maps -- and maintain bash3 compatibility (seriously, macos == IE6). Right now it's totally broken.

The above example shows how to accomplish this using Jamie's output. The parser could be made into a function and used for nested arrays of maps as well.

**Comment by briceburg** [comment]
I'm going to come up with an acid test for this

**Comment by jasmith590** [comment]
@briceburg I will try to work on this today at some point, even if it's on the way to TTI

**Comment by briceburg** [comment]
OK so I almost burst my brain trying to serialize mixed content arrays to something bash 3 can parse... and ended up with a simple approach.

https://github.com/jasmith590/COP/commit/52956164fd95046e5db8bef62ade54ee12738cdf cleans up the parser and will JSON.stringify non-scalar values.  We can then re-evaluate these (using cop itself!) to get to their contents.

Here's the example Input:

```yml
---
test:
  key: value
  array_test:
    - file: /path/to/file.txt
    - shell: shell coommand
  mixed_test:
    - "scalar"
    - "scalar with \"quo'te's\""
    - [ "abc", "def" ]
    - key: valiue with spaces
    - key: single_nest
      nest:
        - nestedkey: value
    - key: double_nest
      nest:
        - nestedKey: value
          nest:
            - doubleNestedKey: WORKS!
```

and we get as `shell` output:

```sh
$ bin/cop test/fixtures/array-of-maps.yml --shell
test__key="value"
test__array_test=( "{\"file\":\"/path/to/file.txt\"}" "{\"shell\":\"shell coommand\"}" )
test__mixed_test=( "scalar" "scalar with \"quo'te's\"" "[\"abc\",\"def\"]" "{\"key\":\"valiue with spaces\"}" "{\"key\":\"single_nest\",\"nest\":[{\"nestedkey\":\"value\"}]}" "{\"key\":\"double_nest\",\"nest\":[{\"nestedKey\":\"value\",\"nest\":[{\"doubleNestedKey\":\"WORKS!\"}]}]}" )
```

notice we no longer have Object Object _and_ this output is evaluatable --  so this issue is fixed.

Here's an example on using it:

```
$ eval $(bin/cop test/fixtures/array-of-maps.yml --shell)
$ for value in "${test__array_test[@]}"; do echo "$value"; done
{"file":"/path/to/file.txt"}
{"shell":"shell coommand"}

# so lets recursively call cop...
$ for value in "${test__array_test[@]}"; do echo "$value" | cop --stdin-type json --shell ; done
file="/path/to/file.txt"
shell="shell coommand"
```

This I believe we can work with. 

@SamTay think we can close and get this released for use in dockmaster?
