### ISSUE TITLE
merging behavior ?

### ISSUE THREAD

**Issue by briceburg** [jasmith590/COP#22]
@jasmith590 I have two files (A and B) with similar arrays of maps. It appears that when I merge these, the second file (B) overwrites the array for every index it shares. E.g. if the second file (B) has one entry in its array, it overwrites the first entry of  first file (A). Here's my sample files

**A**
```yml
---
description: I am your application statellite, ready to launch captain.

# configuration file(s) written to default/conf.d/
mkconf:
  - file: 00-app.yml
    vars:
      - name: APP_REPO
        description: application repository, e.g. git@github.com:org/application.git
      - name: APP_ROOT
        description: application directory relative to the repository root, e.g. webroot
      - name: APP_REPO_KEY
        description: key used to interact with application repository. typically a read-only deployment key
        value: github-ro.key

  - file: 00-skel.yml
    vars:
      - name: SKEL_REPO
        value: git@github.com:BlueAcornInc/devops-skel.git
      - name: SKEL_VERSION
        value: 0.0.0-prototype
```

**B**
```yml
---
description: I am your magento 1 statellite, ready to launch captain.

# configuration file(s) written to default/conf.d/
mkconf:
  - file: 00-app.yml
    vars:
      - name: APP_TYPE
        value: m1
```

and result

```sh
$ badevops-cop mkconf.common.yml mkconf.m1.yml --json
{
  "description": "I am your magento 1 statellite, ready to launch captain.",
  "mkconf": [
    {
      "file": "00-app.yml",
      "vars": [
        {
          "name": "APP_TYPE",
          "description": "application repository, e.g. git@github.com:org/application.git",
          "value": "m1"
        },
        {
          "name": "APP_ROOT",
          "description": "application directory relative to the repository root, e.g. webroot"
        },
        {
          "name": "APP_REPO_KEY",
          "description": "key used to interact with application repository. typically a read-only deployment key",
          "value": "github-ro.key"
        }
      ]
    },
    {
      "file": "00-skel.yml",
      "vars": [
        {
          "name": "SKEL_REPO",
          "value": "git@github.com:BlueAcornInc/devops-skel.git"
        },
        {
          "name": "SKEL_VERSION",
          "value": "0.0.0-prototype"
        }
      ]
    }
  ]
}
```

Notice APP_ROOT from first is gone. I'm not sure if this is expected behavior -- but if it is, will need to modify the way I do things to something way less DRY ;)

Thanks!
