### ISSUE TITLE
add ability to limit sourced configuration

### ISSUE THREAD

**Issue by briceburg** [jasmith590/COP#23]
Lets add the ability to limit (or "filter") sourced configuration to specified root-level key names only. For instance if we read in configuration that looks like

```yml
---
# a.yml
yummyarray:
  - values
  - i
  - want

array:
  - values
  - i
  - dont't 
  - want
```

```yml
---
#b.yml
hello: world
goodnight: moon
```

I'd like to be able to only return `yummyarray` and `goodnight` via something like;

```sh
$ cop --yml a.yml b.yml --limit=goodnight --limit=yummyarray
```

=>

```yml
---
yummyarray:
  - values
  - i
  - want
goodnight: moon
```
