### ISSUE TITLE
confusing error output

### ISSUE THREAD

**Issue by briceburg** [jasmith590/COP#28]
On reading from a malformed yaml file I am seeing;

```
/build/lib/modules/yaml.js:15
    throw "Error loading yaml file '" + filename + "'";
                                        ^

ReferenceError: filename is not defined
    at Object.exports.load (/build/lib/modules/yaml.js:15:41)
    at Object.exports.load (/build/lib/cop.js:39:43)
    at Object.exports.gatherInputs (/build/lib/cop.js:76:21)
    at output (/build/bin/cop:102:15)
    at Object.<anonymous> (/build/bin/cop:47:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
bin/mkconf: eval: line 123: syntax error near unexpected token `('
```

is it possible to limit output and print the YAMLException to stderr?

**Comment by briceburg** [comment]
example yaml file that's throwing an exception

```
[nesta@hartford dist]$ cat /home/nesta/git/devops-prototype-skel/dist/lib/mkconf/global-00-base.yml
---
description: global client configuration
mkconf:
  - file: __client.yml
    vars:
      - name: CLIENT_CODE
        description: identifying code, e.g. YETI
        default: $CLIENT_CODE
        after: after-export

   - file: __platform.yml
     vars:
       - name: PLATFORM_REPO
         value: "$PLATFORM_REPO"
         description: "Satellites R Us Repository, typically git@github.com:BlueAcornInc/devops-skel.git"
         default: git@github.com:BlueAcornInc/devops-prototype-skel.git
       - name: PLATFORM_DEFAULT_REF
         value: "$PLATFORM_DEFAULT_REF"
         description: "git ref holding platform tree. Used by GC updater"
       - name: PLATFORM_VERSION
         overwrite: true
         value: "$PLATFORM_VERSION"
       - name: PLATFORM_TYPE
         overwrite: true
         value: "$PLATFORM_TYPE"
```
